// generated by mBlock5 for mBot
// codes make you happy

#include <MeMCore.h>
#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>

float dist = 0;
float lineFollowerVal = 0;
float traj = 0;
float accel = 0;
float speed_mult = 0;

void init_vars () {
    dist = 0;
    accel = 0;
}

MeLineFollower linefollower_2(2);
MeDCMotor motor_9(9);
MeDCMotor motor_10(10);

void move(int direction, int speed) {
    int leftSpeed = 0;
    int rightSpeed = 0;
    if(direction == 1) {
        leftSpeed = speed;
        rightSpeed = speed;
    } else if(direction == 2) {
        leftSpeed = -speed;
        rightSpeed = -speed;
    } else if(direction == 3) {
        leftSpeed = -speed;
        rightSpeed = speed;
    } else if(direction == 4) {
        leftSpeed = speed;
        rightSpeed = -speed;
    }
    motor_9.run((9) == M1 ? -(leftSpeed) : (leftSpeed));
    motor_10.run((10) == M1 ? -(rightSpeed) : (rightSpeed));
}

MeRGBLed rgbled_7(7, 2);

void follow_line () {
    lineFollowerVal = linefollower_2.readSensors();
    speed_mult = 1 * accel;

    if(lineFollowerVal == 0.000000)
    {
        move(1, speed_mult * 100 / 100.0 * 255);
    } 
    else
    {
        if(lineFollowerVal == 1.000000)
        {
            motor_9.run(-1 * (speed_mult * 28 / 100.0 * 255));
            motor_10.run(speed_mult * 100 / 100.0 * 255);
        } 
        else
        {
            if(lineFollowerVal == 2.000000)
            {
                motor_9.run(-1 * (speed_mult * 100 / 100.0 * 255));
                motor_10.run(speed_mult * 28 / 100.0 * 255);
            }
            else
            {
                accel = 0;
                speed_mult = 0.2;
                move(2, 0.5 * 100 / 100.0 * 255);
                rgbled_7.setColor(0, #faff00);
                rgbled_7.show();
            }
        }
    }
}

MeUltrasonicSensor ultrasonic_3(3);

void _delay(float seconds) {
    long endTime = millis() + seconds * 1000;
    while(millis() < endTime) _loop();
}

void setup() {
    pinMode(A7, INPUT);

    while(!((0 ^ (analogRead(A7) > 10 ? 0 : 1))))
    {
        _loop();
        _delay(0.001);

        if(accel == 0.000000) {
            accel = 0.25;
        }

        accel += 0.001;

        rgbled_7.setColor(0, #a5ff00);
        rgbled_7.show();

        dist = ultrasonic_3.distanceCm();
        if(dist < 20) {
            if(dist < 12) {
                rgbled_7.setColor(0, #ff0000);
                rgbled_7.show();
                accel = 0;
            }
            else {
                if(dist < 16) {
                    rgbled_7.setColor(0, #00b6ff);
                    rgbled_7.show();

                    if(accel > 0.5){
                        accel = 0.5;
                    }
                }
                else {
                    rgbled_7.setColor(0, #00f2ac);
                    rgbled_7.show();

                    if(accel > 0.75) {
                        accel = 0.75;
                    }
                }
                if(accel == 0.000000){
                    _delay(0.5);
                }
            }
        }
        else {
            if(accel > 1) {
                accel = 1;
            }
        }

        follow_line();
    }

    motor_9.run(0);
    motor_10.run(0);
    rgbled_7.setColor(0, #7b5050);
    rgbled_7.show();
    _delay(0.1);
    rgbled_7.setColor(0, 0, 0, 0);
    rgbled_7.show();
}

void _loop() {

}

void loop() {
    _loop();
}
